<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">
    <?php
        
        //var_dump(array_keys($this->national_consumption_by_method)); exit;
    ?>
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  //require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div align="right"><font size="4"><label><?php echo 'National Contraceptive Prevalence Rate 15% Target 36%'; ?></label></font></div>
				
				<div class="hrNav"></div>
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="width: 53%;"> 
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart11_div" style="width: 100%; height: 300px;"></div>
                                                                        <!--<div style="text-align: center;margin-top: 10px; font-weight: bold;">
                                                                            <small>Male Condom Figures x10</small>
                                                                        </div>-->
                                                                    </div>
								
                                                                    <div class="main-search" style="width: 47%;">
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart12_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
                                                                    
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
                                                                    <div class="sliderdiv" style="width: 53%;">
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart13_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
								
                                                                    <div class="main-search" style="width: 47%;">
                                                                        <div class="hrNav"></div>
                                                                        <div id="chart14_div" style="width: 100%; height: 300px;"></div>
                                                                    </div>
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								<div class="main-search"></div>
					</div>
				</div>
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

<?php 
    //var_dump($this->facs_providing_stockedout);  
    //$this->national_percent_facilities_providing = array();
    //$this->national_percent_facilities_stock_out = array();
?>
                
<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
		
	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;
		 
  }


  function drawChart11() {
	  // Create and populate the data table.
          //,{ role: 'style' }
	var chart11Data = google.visualization.arrayToDataTable([
            ['', ''],
        <?php
             foreach ($this->consumption_by_method as $key=>$row){
                        $consumption = $row['consumption'];
                        $malecondoms = 0;
                        $method = $row['method'];
                        $color = 'blue';

                        if($key == 1){
                            //$malecondoms = $consumption;
                            $consumption = round($consumption/10,0);  
                            $method = $row['method'] . '(unit x10)';
                        } 
                ?>
                        [<?php echo  "'$method', $consumption"; ?>],
                <?php
                        }
                ?>
        ]);


                  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;

                  var title_data = <?php echo "'Consumption by Method, $this->title_date'"; ?>;

                  var chart11Options = {  
                              title: title_data,
                              titleTextStyle: { fontSize: 16 },
                              is3D:true,
                              legend: 'none',
                              groupWidth : 10,
                              hAxis : {textStyle: {fontSize: 12}}                      
                        };

                  var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
                  chart11.draw(chart11Data, chart11Options);
   }
  
  
  function drawChart12() {
      var chart12Data = google.visualization.arrayToDataTable([
        [' ', 
         '% of facilities with FP or LARC-trained HW', 
         '% of FP or LARC trained facilities providing FP or LARC', 
         '% of FP or LARC trained facilities stocked out of FP or implants'],
        [ 'FP', <?php echo round($this->csummary['cs_fp_trained_facility_count']*100,2); ?> , <?php echo round($this->csummary['cs_fp_consumption_facility_count']*100,2);?>,<?php echo round($this->csummary['cs_fp_stock_out_facility_count']*100,2);?> ],
        [ 'LARC', <?php echo round($this->csummary['cs_larc_trained_facility_count']*100,2); ?>,<?php echo round($this->csummary['cs_larc_consumption_facility_count']*100,2)?>,<?php echo round($this->csummary['cs_larc_stock_out_facility_count']*100,2)?> ],	        
      ]);

      <?php //echo  " var title_data = 'Coverage summary, $this->cs_date ' " ?>;
      
      //var date = <?php //echo "'" . $this->csummary['cs_date'] . "'"; ?>;
      var title_data = <?php echo "'HR Summary, $this->title_date '"; ?>;

      var chart12Options = {
    		  title: title_data,
    		  titleTextStyle: { fontSize: 16 },
    		  bar: {groupWidth: "80%"},
    		  vAxis: {format: '#\'%\''}, //new
    		  chartArea: {width: '50%', left: 80},//new

                  legend: {textStyle: {'margin-bottom': '100px'}}
                  //vAxis: { ticks: [{v:1, f:'1%'}, {v:2, f:'2%'}, {v:3, f:'3%'}, {v:4, f:'4%'}] }
                  //% of FP or LARC trained facilities stocked out of FP or implants
      };

      var chart12 = new google.visualization.ColumnChart(document.getElementById('chart12_div'));

      chart12.draw(chart12Data, chart12Options);
  }
  
  
  function drawChart13() {
	  
      var chart13Data = google.visualization.arrayToDataTable([
        ['Month', 'FP', 'LARC'],            
            
                    <?php 
                        //$locationNamesArray = explode(',', $locationNames);

                        if(!empty($this->fp_facs_providing)){
                            foreach ($this->fp_facs_providing as $key=>$value){ 
                                $month = $this->fp_facs_providing[$key]['month'];
                                $fp_percent = round($this->fp_facs_providing[$key]['percent'] * 100,2);
                                $larc_percent = round($this->larc_facs_providing[$key]['percent'] * 100,2);
                        ?>
                                [<?php echo "'$month', $fp_percent, $larc_percent"; ?>],

                        <?php
                                }//end foreach
                            } //end if
                        ?>
        ]);

              <?php echo  " var title_data = 'Percent of Facilities Providing FP and LARC, " . $this->start_date . " to " . $this->end_date ."' " ?>;

              var chart13Options = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#\'%\''},
                legend: {textStyle: {'margin-bottom': '100px', 'margin-top': '50px'}, position: 'bottom'}
              };

              var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));
              chart13.draw(chart13Data, chart13Options);

    }
    
    
    
    function drawChart14() {


        var chart14Data = google.visualization.arrayToDataTable([
        ['Month', 
         '% FP facilities stocked out of any FP commodity for 7 days', 
         '% implant facilities stocked out of implants'],

        <?php
//        $start_date = '';
//        $end_date = '';
//        for($i=0; $i<count($this->national_percent_facilities_stock_out); $i++){
//                $row = $this->national_percent_facilities_stock_out[$i];
//                if($i == 0)
//                        $start_date = $row[month] . " " . $row[year];
//                if($i == count($this->national_percent_facilities_stock_out)-1)
//                        $end_date = $row[month] . " " . $row[year];
//                //foreach ($this->national_percent_facilities_stock_out as $row){
//                ?>
                //[//<?php //echo  " '$row[month]'," . round($row[seven_days_percent],2)*100 . "," . round($row[implant_percent],2)*100 ?>],
                <?php
//                        }
                ?>
                            
               <?php 
                    //$locationNamesArray = explode(',', $locationNames);

                    if(!empty($this->facs_providing_stockedout)){
                        foreach ($this->facs_providing_stockedout as $key=>$monthProviders){ 
                            $month = $monthProviders['month'];
                            $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,2);
                            $implant_percent = round($monthProviders['implant_percent'] * 100,2);
                    ?>
                            [<?php echo "'$month', $seven_days_percent, $implant_percent"; ?>],

                    <?php
                            }//end foreach
                        } //end if
                    ?>

        ]);

             <?php echo  " var title_data = 'Stock Outs, " . $this->start_date . " to " . $this->end_date ."' " ?>;

              var chart14Options = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#\'%\'', minValue: 4},
                chartArea: {width: '90%', left: 60},//new
                legend: {textStyle: {'margin-bottom': '100px', 'margin-top': '100px'}, position: 'bottom'}
              };

              var chart14 = new google.visualization.LineChart(document.getElementById('chart14_div'));

              chart14.draw(chart14Data, chart14Options);

   }

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

