<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	position: relative;
}

#homecontent-mid {
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px; 
}

.sliderdiv {
	float: left;
}

.main-search {
	float: left;
	overflow: hidden;
}

.nav-buttons {
	float: left;
	overflow: hidden;
}


</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
    function checkCommoditySelection(){
        console.log('inside check');
        var combo = document.getElementById("comm_id");
        console.log(combo.selectedIndex);
        return false;
    }
</script>

</head>
<body class="yui-skin-sam">
    
    <?php   
            //echo 'high<br/><br/>' ;
            //var_dump($this->consumption_by_method); 
            //var_dump($this->consumption_overtime); exit; 
    ?>
    
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php ///require_once('views/scripts/consumption/top_buttons.phtml');?>
                                <?php require_once('views/scripts/consumption/top_buttons.phtml');?>
			</div>
			<div class="hrNav"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
			</div>
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>
			
			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div class="hrNav"></div>
				<div class="hrNav"></div>
				
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 650px; height: 300px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>
										<div id="chart12_div" style="width: 350px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
					                <div class="hrNav"></div>
									<div id="chart13_div" style="width: 650px; height: 300px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>									
										<div id="chart14_div" style="width: 350px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								<div class="main-search"></div>
					</div>
					
				</div>
				
				
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->


<script type="text/javascript">
    //console.log(<?php echo json_encode($this->consumption_by_method); ?>);
    
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
        <?php if(isset($this->consumption_overtime)) { ?>
            drawChart13();
        <?php } ?>
        
	//var currentLevel;
	//currentLevel = <?php //echo '\'' . $this->location_data[0][name] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("latest_consumption_data=", $this->latest_consumption_data,"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  }

  
  
function drawChart11() {
	  // Create and populate the data table.
          //,{ role: 'style' }
	var chart11Data = google.visualization.arrayToDataTable([
            ['', ''],
<?php
     foreach ($this->consumption_by_method as $key=>$row){
                $consumption = $row['consumption'];
                $malecondoms = 0;
                $method = $row['method'];
                //$color = 'blue';
                
                if($key == 1){
                    //$malecondoms = $consumption;
                    $consumption = round($consumption/10,0);  
                    $method = $row['method'] . '(unit x10)';
                } 
  	?>
                [<?php echo  "'$method', $consumption"; ?>],
  	<?php
  		}
  	?>
]);
	    

	  <?php //echo  " var title_date = 'Monthly Consumption by Method$this->title_date ' " ?>;
          
          var title_data = <?php echo "'Consumption by Method, $this->date'"; ?>;
	  
	  var chart11Options = {  
                      title: title_data,
                      titleTextStyle: { fontSize: 16 },
		      is3D:true,
		      legend: 'none',
                      groupWidth : 10,
                      hAxis : {textStyle: {fontSize: 12}},
                      chartArea: {width: '70%', height: '70%', top: 55}
		};

	  var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
	  chart11.draw(chart11Data, chart11Options);
}



function drawChart13() {
        <?php 
                $commNames = '';
                reset($this->consumption_overtime);
                $firstElement = current($this->consumption_overtime);
                
                foreach($firstElement as $key=>$commodity){                    
                    if($key == "Male Condoms"){
                        $commNames .= "'$key (unit x10)',";
                    } 
                    else{
                        $commNames .= "'$key',";
                    }
                }
                
                $commNames = substr($commNames, 0, -1);
                $legend = "'Month'," . "$commNames";
                //echo $legend;
         ?>                        
         console.log('legend: ' + <?php echo $legend; ?>);
         
        var chart13Data = google.visualization.arrayToDataTable([
                            [<?php echo $legend; ?>],
            <?php 
                foreach ($this->consumption_overtime as $key=>$commValues){ 
                    $month = $key; 
                    $female_condoms = $commValues['Female Condoms'];
                    $male_condoms = round($commValues['Male Condoms']/10,0);
                    $injectables = $commValues["Injectables"];
                    $implants = $commValues["Implants"];
                    $iucds = $commValues["IUCDs"];
                    $oral_pills = $commValues["Oral Pills"];
                    $sterilization = $commValues["Sterilization"]; 
            ?>
                <?php 
                    $consString ='';
                    //foreach ($commValues as $consValue){ 
                        //$consString .= "'" . $consValue . "',";
                    
                    //$consString = substr($consString, 0, -1);
                ?>
                    [<?php echo "'$month', $female_condoms, $male_condoms, $injectables, $implants, $iucds, $oral_pills, $sterilization"; ?>],
                     
            <?php
                    //}
                } 
            ?>
       ]);
        
        
        <?php echo  " var title_data = 'Consumption of FP Commodities $this->start_date to $this->end_date ' " ?>;
                
        var chart13Options = {
		      title: title_data,
		      titleTextStyle: { fontSize: 15 },
		      vAxis: {format: '#', minValue: 4},
		      legend: {fontSize: 14},
		      chartArea: {width: '65%', height: '70%', top: 55},
		      is3D:true
		};

          var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));
	  chart13.draw(chart13Data, chart13Options);

    }
  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

