<?php
	if (isset ($_GET['csv'])){

		$data = array();
		
		$_row = array();
		foreach ($this->headers as $key=>$value){
			$_row[] = $value;
		}
		$data[] = $_row;
		
		foreach ($this->output as $row){
			$_row = array();
			foreach ($row as $key=>$value){
				$_row[] = $value;
			}
			$data[] = $_row;
		}
		


		$delimiter = ',';
		$enclosure = '"';
		$encloseAll = false;
		$nullToMysqlNull = false;
	
		$delimiter_esc = preg_quote($delimiter, '/');
		$enclosure_esc = preg_quote($enclosure, '/');
	
		$output = array();
if(isset($this->criteria['total_participants'])){
                                    $output[] = "Total Participants: ".$this->criteria['total_participants']."";
                                }  else if(isset($this->criteria['total_training'])) {
                                    $output[] = "Total Trainings: ".$this->criteria['total_training']."";
                                } 
		foreach ($data as $row){
			$outputrow = array();
			foreach ($row as $field){
				if ($field === null && $nullToMysqlNull) {
					$outputrow[] = 'NULL';
					continue;
				}
		
				// Enclose fields containing $delimiter, $enclosure or whitespace
				if ( $encloseAll || preg_match( "/(?:${delimiter_esc}|${enclosure_esc}|\s)/", $field ) ) {
					$outputrow[] = $enclosure . str_replace($enclosure, $enclosure . $enclosure, $field) . $enclosure;
				}
				else {
					$outputrow[] = $field;
				}
			}
                        //$output[] = "Total Participants: ".$this->criteria['total_participants']."";
                      
                              
			$output[] = implode($delimiter,$outputrow);
		}
		$output = implode("\n", $output);

		header("Content-type: text/csv");
		header("Content-Disposition: attachment; filename=facility-report-" . date("d.m.Y.H.m.s") . ".csv");
		header("Pragma: no-cache");
		header("Expires: 0");
		echo $output;
		exit;
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Training Reports');?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		?>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );
		</script>
	</head>
    <style type="text/css">
        
        select{
            
      
           
        }
        .mclass{
    min-height:100px;
    max-width:200px;
    
}
        </style>
        <script type="text/javascript">
            function check_verify(id){
                
                var val = document.getElementById(id).value;
               
                //alert('This is the value '+val);
                if(val=="view_individual_train" || val=="view_aggregate_train"){
                    document.getElementById("province_id").disabled=true;
                    document.getElementById("district_id").disabled=true;
                    document.getElementById("region_c_id").disabled=true;
                }else{
                   document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=false; 
                }
                
            }
            function check_buttons(){
               var val =   forms.aggregate_method.value;
                if(val=="view_individual_train" || val=="view_aggregate_train"){
                    document.getElementById("province_id").disabled=true;
                    document.getElementById("district_id").disabled=true;
                    document.getElementById("region_c_id").disabled=true;
                }else{
                   document.getElementById("province_id").disabled=false;
                    document.getElementById("district_id").disabled=false;
                    document.getElementById("region_c_id").disabled=false; 
                }
            }
            </script>
	<body class="yui-skin-sam" onload="check_buttons()" >
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content">
				<div id="subcontent">
					<div id="contentheader">
						<h2><?php tp('Training Reports');?></h2><br>
					</div>
					<div class="pad50 clear"></div>
                                         <?php 
                                                    // print_r($this->criteria['error']);
                                                     foreach($this->criteria['error'] as $error){
                                                         echo '<h3 align="center" style="color:red;"><b>* '.$error.'</b></h3>';
                                                     }
                                                     ?>
					<form  action="" method="get" name="forms">
						
					<input type="hidden" name="process" id="process" value="1">
					<br/>

							<div class="pad20 clear"></div>

                                                
                                                 <div  class="queryquestion" style="width:84%; margin:0 auto;">
                                                    <?php
                                                     ////echo 'This is the thing you dnt do in school '.$this->criteria['aggregate_method']; ?>
                                                    View Participant Names&nbsp; <input type="radio" name="aggregate_method" onclick="check_verify('view_part_names')" value="view_part_names" id="view_part_names" <?php if($this->criteria['aggregate_method']=="view_part_names"){ echo "checked='checked'";} ?>/> &nbsp;&nbsp;&nbsp;
                                                    View Aggregate Participants&nbsp; <input type="radio" name="aggregate_method" onclick="check_verify('view_aggregate_part')" id="view_aggregate_part" value="view_aggregate_part" <?php if($this->criteria['aggregate_method']=="view_aggregate_part"){ echo "checked='checked'";} ?>/>  
                                                    View Aggregate Trainings&nbsp;    <input type="radio" name="aggregate_method" onclick="check_verify('view_aggregate_train')" value="view_aggregate_train"  id="view_aggregate_train" <?php if($this->criteria['aggregate_method']=="view_aggregate_train"){ echo "checked='checked'";} ?>/>  &nbsp;&nbsp;&nbsp;
                                                    View Individual Trainings &nbsp;    <input type="radio" name="aggregate_method" onclick="check_verify('view_individual_train')" value="view_individual_train" id="view_individual_train" <?php if($this->criteria['aggregate_method']=="view_individual_train"){ echo "checked='checked'";} ?>/> 
                                                
                                                 </div>
                                                        
							
                                                        <div class="clear pad20">&nbsp;</div>
						<div class="pad20 clear"></div>
                                                <fieldset style="width:100%;height:200px; margin:0 auto;">
<div class="maintoucher" >
							<div class="queryquestion">Zone</div><br/>
							
							<div class="queryquestion"><?php renderFilter($this->locations, 1, 'province_id', $this->criteria['province_id'], 'district_id', false,false,'10'); ?></div>
</div>
							<div class="maintoucher" >
	
							<div class="queryquestion">State</div><br/>
							
							<div class="queryquestion"><?php renderFilter($this->locations, 2, 'district_id', $this->criteria['district_id'], 'region_c_id', true,false,'10'); ?></div>
                                                        </div>
							<div class="maintoucher" >
	
							<div class="queryquestion">LGA</div><br/>
							
							<div class="queryquestion"><?php renderFilter($this->locations, 3, 'region_c_id', $this->criteria['region_c_id'],'facility_id', true, false,'10'); ?></div>
							
                                                        </div>

							<!-- TA:17: 09/04/2014 START-->
<?php ?><div class="maintoucher" >
                                                        <div class="queryquestion">Facility</div><br/>
							<div class="queryquestion">
<?php renderFilter($this->locations, 4, 'facility_id', $this->criteria['facility_id'],'', true, false,'10'); ?></div><br/>
</div>
							<div class="maintoucher" >
							<div class="queryquestion"><?php echo t('Training Type'); ?></div><br/>
							
							<div class="queryquestion"><select name="training_type[]" id="trainingtype" multiple size="10" style="width:190px;">
<?php
echo "<option value='' disabled >--choose--</option>";
	foreach ($this->trainingtypes as $item){
            if(in_array($item['id'],$this->criteria['training_type'])){
                $selected = "selected='selected'";
            }else{
                $selected = "";
            }
		echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['training_title_phrase']."'>" . $item['training_title_phrase'] . "</option>\n";
	}
?>
							</select></div></div>
                                        </fieldset>
							    <fieldset style="width:100%;height:200px; margin:0 auto;">
							<div class="maintoucher" >

							<div class="queryquestion"><?php echo 'Training Organizer'; ?></div><br/><br/>
							
							<div class="queryquestion">
                               <select name="trainingorganizer[]" id="trainingorganizer"  multiple size="10" style="width:190px">
	<?php
         echo "<option value='' disabled>--choose--</option>";
		foreach ($this->trainingorganizer as $item){
                   if(in_array($item['id'],$this->criteria['trainingorganizer'])){
                $selected = "selected='selected'";
            }else{
                $selected = "";
            }
			echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['training_organizer_phrase']."'>" . $item['training_organizer_phrase'] . "</option>\n";
		}
	?>
							</select></div></div>
                                                        <div class="maintoucher" >
							
	<div class="queryquestion"><?php echo t('Trained (End Date)'); ?></div><br/>
							
							<div class="querylongerdates">
                                                           
                                                           <div class="queryq" id="startdate" style="float:left">
                                                               
                                                               
																 <input id="start-day" class="dayfield" type="text" placeholder="DD" name="start-day" maxlength="2" size="2" value="<?php echo $this->criteria['start_day']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;" />
																 <input id="start-month" class="monthfield" type="text" placeholder="MM" name="start-month" maxlength="2" size="2"value="<?php echo $this->criteria['start_month']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;"  />
																 <input id="start-year" class="yearfield" type="text" placeholder="YYYY" name="start-year" maxlength="4" size="4" value="<?php echo $this->criteria['start_year'];  ?>" style="width : 50px; margin-right : 10px; margin-left : 0px;" />
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeCalendar("startdate","start-day", "start-month", "start-year");
																	});
																</script>
															
                                                           </div>          <br/>
                                                            <div class="queryquestion" > to &nbsp;</div>      <br/>
                                                                        
                                                                                
                                                                                
                                                                                
                                                                                     
															<div class="queryq" style="float:right" id="enddate" style="margin-top:1em;">
																 <input id="end-day" class="dayfield" type="text" placeholder="DD" name="end-day" maxlength="2" value="<?php echo $this->criteria['end_day']; ?>"  style="width : 30px; margin-right : 10px; margin-left : 0px;"/>
																 <input id="end-month" class="monthfield" type="text" placeholder="MM" name="end-month" maxlength="2" value="<?php echo $this->criteria['end_month']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;" />
																<input id="end-year" class="yearfield" type="text" name="end-year" placeholder="YYYY" maxlength="4" value="<?php echo $this->criteria['end_year'];  ?>" style="width : 50px; margin-right : 10px; margin-left : 0px;"/>
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
																	});
																</script>
															</div>   
                                                        </div>
                                                      
                                                       

						</div>
                                                        <div class="maintoucher" >
							<div class="queryquestion"><?php echo t('Professional Qualification'); ?></div><br/><br/>
							
							<div class="queryquestion"><select name="cadre" style="width:190px;" />
	<?php
       
        echo "<option value=''  ".$disbaled.">--choose--</option>";
		foreach ($this->qualifications as $item){
                    if($item['id']== $this->criteria['cadre']){
                        $selected = "selected='selected'";
                    }else{
                        $selected = "";
                    }
			echo "<option value=\"" . $item['id'] . "\" ".$selected." title='".$item['qualification_phrase']."'>" . $item['qualification_phrase'] . "</option>\n";
		}
	?>
							</select></div><br/><br/>
                                                        <div class="queryquestion">Certification</div><br/>
							
							<div class="queryquestion"><select name="certification" style="max-height:25px; width:;"> 
                                                                <option value="" >--choose</option>
                                                                <option value="Yes" <?php if($this->criteria['certification']=="Yes") echo 'selected="selected"';?>>Yes</option>
                                                                <option value="No" <?php if($this->criteria['certification']=="No") echo 'selected="selected"';?>>No</option>
                                                            </select>    </div>                                                        
                                                        </div>
                                                        <div class="maintoucher" >
                                              <div class="queryquestion">Gender</div><br/><br/>
							
							<div class="queryquestion"><select name="gender" style="max-height:25px; width:;"> 
                                                                <option value="" >--choose--</option>
                                                                <option value="male" <?php if($this->criteria['gender']=="male") echo 'selected="selected"';?>>Male</option>
                                                                <option value="female" <?php if($this->criteria['gender']=="female") echo 'selected="selected"';?>>Female</option>
                                                            </select>    </div> <br/><br/>                                                       
                                                        
	<div class="queryquestion"><?php echo t('Date of Birth'); ?></div><br/>

							<div class="querylongerdates">
                                                           
                                                           <div class="queryq" id="dobstartdate" style="float:left">
                                                               
                                                               
																 <input id="dob-start-day" class="dayfield" type="text" placeholder="DD" name="dob-start-day" maxlength="2" size="2" value="<?php echo $this->criteria['dob_start_day']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;" />
																 <input id="dob-start-month" class="monthfield" type="text" placeholder="MM" name="dob-start-month" maxlength="2" size="2"value="<?php echo $this->criteria['dob_start_month']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;"  />
																 <input id="dob-start-year" class="yearfield" type="text" placeholder="YYYY" name="dob-start-year" maxlength="4" size="4" value="<?php echo $this->criteria['dob_start_year'];  ?>" style="width : 50px; margin-right : 10px; margin-left : 0px;" />
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeCalendar("dobstartdate","dob-start-day", "dob-start-month", "dob-start-year");
																	});
																</script>
															
                                                           </div>          <br/>
                                                            <div class="queryquestion" > to &nbsp;</div>      <br/>
                                                                        
                                                                                
                                                                                
                                                                                
                                                                                     
															<div class="queryq" style="float:right" id="dobenddate" style="margin-top:1em;">
																 <input id="dob-end-day" class="dayfield" type="text" placeholder="DD" name="dob-end-day" maxlength="2" value="<?php echo $this->criteria['dob_end_day']; ?>"  style="width : 30px; margin-right : 10px; margin-left : 0px;"/>
																 <input id="dob-end-month" class="monthfield" type="text" placeholder="MM" name="dob-end-month" maxlength="2" value="<?php echo $this->criteria['dob_end_month']; ?>" style="width : 30px; margin-right : 10px; margin-left : 0px;" />
																<input id="dob-end-year" class="yearfield" type="text" name="dob-end-year" placeholder="YYYY" maxlength="4" value="<?php echo $this->criteria['dob_end_year'];  ?>" style="width : 50px; margin-right : 10px; margin-left : 0px;"/>
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeAdditionalCalendar("dobenddate","dob-end-day", "dob-end-month", "dob-end-year");
																	});
																</script>
															</div>   
                                                        </div>
													

                                                        </div>
                                                            </fieldset>
                                                        <div class="clear pad20">&nbsp;</div>
						
						<div class="mainformholder" style="height : 100px;">
							<div  style="float : right;" >
								<input type="submit" name="go" value="<?php tp('Preview');?> &raquo;" class="tsbutton green large">
							</div>
							<div class="clear pad20">&nbsp;</div>
						</div>
						<div class="clear pad20">&nbsp;</div>
					</form>
                                       

<?php
 //print_r($this->tocktack);

if (isset($this->output)) {
	if (count ($this->output) == 0){
		echo "				<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display tablegrid\" id=\"\" style=\"width:100%\">\n";
		echo "					<thead>\n";
		echo "						<tr>\n";
		echo "							<th>".t('Output')."</th>\n";
		echo "						</tr>\n";
		echo "					</thead>\n";
		echo "					<tbody>\n";
		echo "						<tr>\n";
		echo "							<td>".t("Your search criteria returned no results")."</td>\n";
		echo "						</tr>\n";
		echo "					</tbody>\n";
		echo "				</table>\n";
	} else {
?>

				<br>
                                    <?php if(isset($this->criteria['total_participants'])){
                                    echo "<h3><b><i>Total Participants:  ".$this->criteria['total_participants']."</i></b></h3>";
                                    
                                }  else if(isset($this->criteria['total_training'])) {
                                    echo "<h3><b><i>Total Trainings:  ".$this->criteria['total_training']."</i></b></h3>";
                                } 
                                ?>
                                <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
<?php
		foreach ($this->headers as $key=>$value){
			echo "							<th>" . $value . "</th>\n";
		}
?>
						</tr>
					</thead>
					<tbody>
<?php
		foreach ($this->output as $row){
			echo "						<tr style=\"cursor : pointer;\" class=\"GradeA\">\n";
			foreach ($row as $key=>$value){
				echo "				   			<td>" . $value . "</td>\n";
			}
			echo "						</tr>\n";
		}
?>
					</tbody>
				</table>
				<input type="button" name="go" value="<?php tp('Download');?> &raquo;" class="tsbutton green large" onclick="window.open('<?php
$_GET['csv'] = 1;
$url = $_SERVER['REQUEST_URI'] . "&csv=1";
#foreach ($_GET as $key=>$value){
#	$url .= $key . "=" . $value . "&";
#}
echo $url;  ?>')">
<?php
	}
}
?>
					<div class="clear" style=""></div>
				</div>
				<div class="clear" style=""></div>
			</div>   
			<div class="clear" style="height : 100px;"></div>
			<div class="clear" style=""></div>
							
	
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
	</body>
</html>






